<?php

namespace AppBundle\Repository;

/**
 * ProduitCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCommandeRepository extends \Doctrine\ORM\EntityRepository
{

	public function montantTotal()
	{
	    $qb = $this->createQueryBuilder('pc')
	    ->select('SUM(pc.qte * pc.prix)')
	    ->getQuery()
	    ->getScalarResult();
	        return $qb[0];
	}

	public function getProductsCommande($id_commande)
	{
		$qb = $this->createQueryBuilder('pc')
	    ->select('pc')
	    ->innerJoin('pc.commande', 'comm')
	    ->innerJoin('pc.produit', 'prod')
    	->where('comm.id = :id_comm')
    	->setParameter('id_comm', $id_commande)
	    ->getQuery()
	    ->getResult();
	    return $qb;
	}
	public function totalHT($id_commande)
	{
		$qb = $this->createQueryBuilder('pc')
	    ->select('SUM(pc.qte*pc.prix)')
	    ->innerJoin('pc.commande', 'comm')
    	->where('comm.id = :id_comm')
    	->setParameter('id_comm', $id_commande)
	    ->getQuery()
	    ->getScalarResult();
	        return $qb[0];
	}
}
