<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \AppBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'libellle', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'descriptCourt', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'descriptLong', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'imagePrin', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'imagesSec', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'categorie'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'libellle', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'descriptCourt', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'descriptLong', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'imagePrin', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'imagesSec', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'prix', '' . "\0" . 'AppBundle\\Entity\\Produit' . "\0" . 'categorie'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibellle($libellle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibellle', [$libellle]);

        return parent::setLibellle($libellle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibellle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibellle', []);

        return parent::getLibellle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptCourt($descriptCourt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptCourt', [$descriptCourt]);

        return parent::setDescriptCourt($descriptCourt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptCourt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptCourt', []);

        return parent::getDescriptCourt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptLong($descriptLong)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptLong', [$descriptLong]);

        return parent::setDescriptLong($descriptLong);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptLong()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptLong', []);

        return parent::getDescriptLong();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagePrin($imagePrin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagePrin', [$imagePrin]);

        return parent::setImagePrin($imagePrin);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagePrin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagePrin', []);

        return parent::getImagePrin();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagesSec($imagesSec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagesSec', [$imagesSec]);

        return parent::setImagesSec($imagesSec);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagesSec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagesSec', []);

        return parent::getImagesSec();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\AppBundle\Entity\Categorie $categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
