<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxbm5al\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxbm5al/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZxbm5al.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZxbm5al\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZxbm5al\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zxbm5al',
    'container.build_id' => 'dcdfede9',
    'container.build_time' => 1546367485,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxbm5al');
